#!/usr/bin/env python3
"""Regenerate ``src/viaduct/data/profanity.txt`` from the public word lists.

Fetches github.com/censor-text/profanity-list, normalises and hashes each word,
and writes only the hashes, so no plaintext slur list ever lands in the repo.

    python tools/build_profanity.py            # english (default)
    python tools/build_profanity.py en es de   # several languages

Committing the regenerated file is a deliberate step, review the diff (it is
just hashes) before you push.
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

from viaduct.profanity import _norm, hash_word

BASE = "https://raw.githubusercontent.com/censor-text/profanity-list/main/list/{}.txt"
OUT = Path(__file__).resolve().parent.parent / "src" / "viaduct" / "data" / "profanity.txt"


def main(langs: list[str]) -> None:
    words: set[str] = set()
    for lang in langs:
        raw = urllib.request.urlopen(BASE.format(lang), timeout=30).read()
        for line in raw.decode("utf-8", "ignore").splitlines():
            word = _norm(line)
            if len(word) >= 2:
                words.add(word)
    maxlen = max((len(w) for w in words), default=0)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("# viaduct profanity hashes; generated by tools/build_profanity.py; do not edit.\n")
        f.write(
            f"# source=github.com/censor-text/profanity-list "
            f"langs={','.join(langs)} count={len(words)} maxlen={maxlen}\n"
        )
        for h in sorted(hash_word(w) for w in words):
            f.write(h + "\n")
    print(f"wrote {len(words)} hashes ({','.join(langs)}, maxlen={maxlen}) -> {OUT}")


if __name__ == "__main__":
    main([a.lower() for a in sys.argv[1:]] or ["en"])
